apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  namespace: blue-orb
spec:
  selector:
    app: microservice  # This matches the labels in the Deployment
  ports:
    - protocol: TCP
      port: 8080        # Port on which the service will be available internally
      targetPort: 8080  # Port that the container listens on
  type: ClusterIP  # Use ClusterIP for internal communication or change to LoadBalancer for external access
